#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 8000
management:
  endpoint:
    health:
      show-details: "NEVER"
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /admin
      path-mapping:
        health: health-check
  health:
    defaults:
      enabled: false
  info:
    env:
      enabled: true
info:
  app:
    name: Certificate
    version: 1.0
spring:
  application:
    name: certificate-microservice
  main:
    allow-bean-definition-overriding: true
  security:
    jwt:
      jwks: ${JWT_WELL_KNOWNS}
      iss: ${JWT_CERT_ISSUER}
      aud: ${JWT_AUDIENCE}
    autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  threads:
    virtual:
      enabled: true
permissions:
  service:
    url: http://permissions-service
    connectionTimeout: 3000
    readTimeout: 3000
  security:
    token-feature-switch: false
frontendNotification:
  service:
    scheme: ${FRONTEND_NOTIFICATION_SERVICE_SCHEME}
    host: ${FRONTEND_NOTIFICATION_SERVICE_HOST}
    port: ${FRONTEND_NOTIFICATION_SERVICE_PORT}
service:
  security:
    token-feature-switch: false
logging:
  pattern:
    correlation: "[ConversationId:%X{ConversationId:-}] "
