config:
  SPRING_PROFILES_ACTIVE: "k8s"
  FRONTEND_NOTIFICATION_SERVICE_HOST: "frontend-notification-blue-tst.azurewebsites.net"
  FRONTEND_NOTIFICATION_SERVICE_PASSWORD: ""
  FRONTEND_NOTIFICATION_SERVICE_PORT: "443"
  FRONTEND_NOTIFICATION_SERVICE_SCHEME: "https"
  FRONTEND_NOTIFICATION_SERVICE_USERNAME: "poc"
